# This is a basic workflow to help you get started with Actions

name: Pipeline MPV

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # Runs a single command using the runners shell
      - name: Build Solution
        run: echo Hello, build!
  Unit_Test:  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Unit Test
    needs: Build
    steps:
        - name: Unit Testing execution
          run: echo Hello, Unit Test!
  Code_analysis:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Code_analysis
    needs: Unit_Test
    steps:
        - name: Sonar Validation
          run: echo Hello, Sonar!
  Functional_Testing:
    # The - name: Sonar Vali the job will run on
    runs-on: ubuntu-latest
    name: Functional_Testing
    needs: Code_analysis
    steps:
        - name: Functional Testing execution
          run: echo Hello, Functional Testing!
  Security_Testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Security_Testing
    needs: Functional_Testing
    steps:
        - name: Security validation
          run: echo Hello, Security Testing!
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Deploy
    needs: Functional_Testing
    steps:
        - name: Security_Testing
          run: echo Hello, Deploy!
  
